In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

job_data = [] 

for i in range(1, 100):
    url = f'https://www.timesjobs.com/candidate/job-search.html?from=submit&luceneResultSize=25&txtKeywords=python&postWeek=60&searchType=personalizedSearch&actualTxtKeywords=python&searchBy=0&rdoOperator=OR&pDate=I&sequence={i}&startPage={i}'
    html_text = requests.get(url).text
    soup = BeautifulSoup(html_text, 'lxml')
    
    jobs = soup.find_all('li', class_="clearfix job-bx wht-shd-bx")
    for job in jobs:
        try:
            job_role = job.find('h2', class_="heading-trun").text.strip()
            company_name = job.find('h3', class_="joblist-comp-name").text.strip()
            updated = job.find('span', class_="sim-posted").text.strip()
            job_description = job.find('li', class_="job-description__").text.strip()
            skill_require = job.find('div', class_="more-skills-sections").text.strip()
            skill_require = ', '.join(word for word in skill_require.split() if word)
            job_location = job.find('li', class_="srp-zindex location-tru").text.strip()

            job_data.append({
                'Company name': company_name,
                'Job Description': job_description,
                'Job Role': job_role,
                'Skills': skill_require,
                'Location': job_location,
                'Updated': updated     
            })
        except AttributeError:
            
            continue

dataset = pd.DataFrame(job_data)

In [ ]:
dataset.pd_tocsv

,Company name,Job Description,Job Role,Skills,Location,Updated
0,art technology and software india pvt ltd,ResponsibilitiesIn-depth knowledge of Python a...,Python Developer,"rest, python, database, django, api",Cochin/ Kochi/ Ernakulam,1 day ago
1,xonier technologies pvt ltd,Roles and ResponsibilitiesCoordinating with de...,Python Developer,"python, django, testing, tools, debugging, sto...",Noida/Greater Noida,1 day ago
2,day1 technologies,Reading Time: Less than 1 minuteJob Requiremen...,Python Developer,"rest, python, django, git, postgresql, sql, do...",Bengaluru / Bangalore,1 day ago
3,east india securities ltd.,job_description 2 years of experience worki...,Python Engineer,"python, hadoop, machine, learning",Kolkata,few days ago
4,CONNECTING 2 WORK,Job Description We are looking for candidates ...,PYTHON TRAINER,"rest, python, django, mongodb",Calicut/ Kozhikode,few days ago
...,...,...,...,...,...,...
2470,infimetrics info solutions pvt. ltd,Job DetailsJob Title: Data Engineer ( 6-9 yea...,Job Title :Data Engineer ( 6-9 years ),"data, engineering, data, modeling, sql, profic...",Pune,few days ago
2471,Odoo,"Odoo Experience Developer 401 & 402 , 4th F...",Odoo Experience Developer,"odoo, framework, knowledge, git, javascript, s...",Gandhinagar,few days ago
2472,Techversant,"ODOO Odoo Developer Infopark , Cochin , Kera...",Odoo Developer,"odoo, development, business, analysis, python,...",Cochin/ Kochi/ Ernakulam,few days ago
2473,Saggio Insurance Marketing Pvt Ltd,Skills Required:Front End- Agile delivery meth...,IAM DevOps Engineer,"css, html5, bootstrap, jquery, java, iam, devo...","Gurgaon, Delhi, Delhi/NCR, Kolkata, Bengal...",few days ago
2474,world resources institute,HomeFAQInternshipsIntern- Geo Analytics Data A...,Intern- Geo Analytics,"geoanalytics, data, analysis, technical, resea...","Mumbai, Delhi, Bengaluru / Bangalore, Delhi...",few days ago

In [12]:
dataset.to_csv('job_data.csv', index=False)